server:
  port: 8084

spring:
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true

# Configuration for user-service client (Feign client)
# This is to ensure this points to where user-service is discoverable
user-service:
  url: http://user-service/api/users # Or lb://user-service/api/users if Feign is Eureka-aware

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080} # Base URL of Keycloak
  realm: library
  client-id: library-client # The client ID auth-service will use to talk to Keycloak
  client-secret: ${KEYCLOAK_CLIENT_SECRET:client-secret} # Client secret for 'library-client' from Keycloak
  token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token

logging:
  level:
    com.librarysystem.authservice: INFO
    com.librarysystem.authservice.client.KeycloakClient: DEBUG

gateway:
  secret: M3lT#9fGz!8qP@Z^rKw!5xL7e2Bj&T0v