services:
  # INFRASTRUCTURE
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      KEYCLOAK_DB: keycloak
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - library-network
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminadmin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - library-network

  # CORE SERVICES  
  discovery-service:
    build: discovery-service
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - library-network
  
  # API Gateway
  api-gateway:
    build: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_URL=http://keycloak:8080
      - EUREKA_URL=http://discovery-service:8761/eureka
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - keycloak
    networks:
      - library-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
        - "8090:8080"
    depends_on:
      - postgres
    networks:
      - library-network

  user-service:
    build: user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library?currentSchema=users
      - SPRING_DATASOURCE_USERNAME=user_service
      - SPRING_DATASOURCE_PASSWORD=userpass
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URL=http://discovery-service:8761/eureka
    depends_on:
      - postgres
      - discovery-service
    networks:
      - library-network

  auth-service:
    build: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URL=http://discovery-service:8761/eureka
      - KEYCLOAK_URL=http://keycloak:8080 
    depends_on:
      - postgres
      - discovery-service
      - user-service
    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge