server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/library?currentSchema=users
    username: user_service
    password: userpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: user-service

logging:
  level:
    com.librarysystem.userservice.security: DEBUG
    org.springframework.security: DEBUG
