server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-postgres:5434/userdb
    username: user_service
    password: userpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

keycloak:
  admin:
    server-url: ${KEYCLOAK_ADMIN_URL:http://keycloak:8080} # URL to Keycloak server
    realm: master                # Admin operations are typically against the master realm
    username: ${KEYCLOAK_ADMIN_USER:admin}                # Keycloak admin username
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}            # Keycloak admin password
    client-id: admin-cli         # Client ID for admin operations
  target-realm: library          # The realm where users will be created

gateway:
  secret: M3lT#9fGz!8qP@Z^rKw!5xL7e2Bj&T0v

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: user-service

logging:
  level:
    com.librarysystem.userservice: DEBUG
    org.springframework.web: DEBUG