apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: book-service
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: book-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: book-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: bookpass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://book-postgres:5432/bookdb
            - name: SPRING_DATASOURCE_USERNAME
              value: book_service_user
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image:  localhost:49990/book-service:latest
          name: book-service
      restartPolicy: Always
