apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: borrow-service
  name: borrow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: borrow-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: borrow-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: borrowpass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://borrow-postgres:5432/borrowdb
            - name: SPRING_DATASOURCE_USERNAME
              value: borrow_service_user
          image: borrow-service
          name: borrow-service
      restartPolicy: Always
