apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: borrow-postgres-data
  name: borrow-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
