apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: discovery-service
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: discovery-service
    spec:
      containers:
        - image: localhost:49990/discovery-service:latest
          name: discovery-service
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
