apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: discovery-service
  name: discovery-service
spec:
  type: NodePort
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
      nodePort: 30861
  selector:
    io.kompose.service: discovery-service
