apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
      nodePort: 30881
  selector:
    io.kompose.service: kafka-ui
