apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  type: NodePort
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8080
      nodePort: 30890
  selector:
    io.kompose.service: keycloak
