apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka
            - name: SPRING_DATASOURCE_PASSWORD
              value: userpass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://user-postgres:5432/userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: user_service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: user-service
          name: user-service
      restartPolicy: Always
